
##### Prefix を Space に #####
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# ここは好み。入れ子 tmux を使わないなら無くてもOK
# bind Space send-prefix

# 時計回り
bind o select-pane -t :.+
# 反時計回り
bind O select-pane -t :.-


##### Space + h/j/k/l で方向移動 #####
bind -T prefix h select-pane -L
bind -T prefix j select-pane -D
bind -T prefix k select-pane -U
bind -T prefix l select-pane -R

##### ついでに覚えやすい：Space + x でペインを閉じる #####
bind -T prefix x kill-pane

##### 設定リロード：Space + r #####
bind -T prefix r source-file ~/.tmux.conf \; display-message "Reloaded!"

# lazygitをフルサイズpopupで開く
bind -T prefix g display-popup -E -w 100% -h 100% -d "#{pane_current_path}" lazygit

##### 分割時にカレントディレクトリを引き継ぐ #####

unbind %
unbind '"'

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# 今のレイアウト文字列を表示（コピー用）
bind L display-message -p "#{window_layout}"

